=== jedi-academy/learn-4711/xml/organizer.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
An organizer presents a trail through the course materials,
organized by "week".
-->

<!--- This course trail is organized by weeks. -->
<!ELEMENT organizer (week)*>

<!--- Each week has a topic, then any number of learning components.
It should have a unique identifier, its "num" attribute. -->
<!ELEMENT week (topic,outcomes?, inlab?, (lesson|tutorial|lab|github|assignment|example)*)>
<!ATTLIST week
    num CDATA #REQUIRED
  >

<!--- Description of the week's main activity. -->
<!ELEMENT topic (#PCDATA)>
<!--- Course goals/outcomes to address. -->
<!ELEMENT outcomes (#PCDATA)>
<!--- Description of intended lab activity. -->
<!ELEMENT inlab (#PCDATA)>

<!--- A lesson contains a description of that lesson.
Attributes include the type (for formatting), the name (identifier), and an
optional link to a downloadable PDF. 
The domain attribute specifies an external domain where this item is hosted. -->
<!ELEMENT lesson (#PCDATA)>
<!ATTLIST lesson
    type CDATA "lesson"
    name CDATA #REQUIRED
    pdf CDATA #IMPLIED
    domain CDATA    #IMPLIED
    active (y|n) "y" 
    icon CDATA #IMPLIED
    survey CDATA #IMPLIED
  >

<!--- A tutorial contains a description of that tutorial.
Attributes include the type (for formatting), the name (identifier), and an
optional link to a downloadable PDF. 
The domain attribute specifies an external domain where this item is hosted. -->
<!ELEMENT tutorial (#PCDATA)>
<!ATTLIST tutorial
    type CDATA "tutorial"
    name CDATA #IMPLIED
    pdf CDATA #IMPLIED
    domain CDATA    #IMPLIED
    active (y|n) "y" 
    icon CDATA #IMPLIED
  >

<!--- A lab contains a description of that lab.
Attributes include the type (for formatting), the name (identifier), 
the due date (yyyy.mm.dd) and an
optional link to a downloadable PDF. 
The domain attribute specifies an external domain where this item is hosted. -->
<!ELEMENT lab (#PCDATA)>
<!ATTLIST lab
    type CDATA "lab"
    name CDATA #IMPLIED
    duedate CDATA #IMPLIED
    pdf CDATA #IMPLIED
    domain CDATA    #IMPLIED
    active (y|n) "y" 
    icon CDATA #IMPLIED
>

<!--- A github element contains a description of the repo linked to.
Attributes include the type (for formatting), the name (identifier), and an
optional link to a github repository. 
The domain attribute specifies an external domain where this item is hosted. -->
<!ELEMENT github (#PCDATA)>
<!ATTLIST github
    type CDATA "github"
    name CDATA #IMPLIED
    link CDATA #IMPLIED
    domain CDATA    #IMPLIED
    active (y|n) "y" 
    icon CDATA #IMPLIED
  >

<!--- An assignment contains a description of that assignment.
Attributes include the type (for formatting), the name (identifier), 
the due date (yyyy.mm.dd) and an
optional link to a downloadable PDF. 
The domain attribute specifies an external domain where this item is hosted. -->
<!ELEMENT assignment (#PCDATA)>
<!ATTLIST assignment
    type CDATA "assignment"
    name CDATA #IMPLIED
    duedate CDATA #IMPLIED
    pdf CDATA #IMPLIED
    domain CDATA    #IMPLIED
    active (y|n) "y" 
    icon CDATA #IMPLIED
  >

<!--- An example contains a description of that example.
Attributes include the type (for formatting), and the name (identifier)
A link will be generated to a zip of the same name 
The domain attribute specifies an external domain where this item is hosted. -->
<!ELEMENT example (#PCDATA)>
<!ATTLIST example
    type CDATA "example"
    name CDATA #IMPLIED
    domain CDATA    #IMPLIED
    active (y|n) "y" 
    icon CDATA #IMPLIED
  >

=== jedi-academy/learn-4711/data/organizer.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE organizer SYSTEM "../xml/organizer.dtd">
<!--
Course organizer for Comp4711
-->
<organizer>
    <week num="1">
        <topic>Introduction to MVC Webapps</topic>
        <outcomes>1.1 (server), 3.2</outcomes>
        <inlab>#1 Development setup</inlab>
        <lesson name="intro00">Course Introduction</lesson>
        <lesson name="intro01" >Introduction</lesson>
        <lab name="lab01">Development Environment</lab>
        <tutorial name="setup01">XAMPP Installation</tutorial>
        <tutorial name="setup02">Virtual Hosting Setup</tutorial>
    </week>
    <week num="2">
        <topic>MVC Frameworks</topic>
        <outcomes>1.1 (PHP), 1.2 (basics),3</outcomes>
        <inlab>#2 Project &amp; Process Prep</inlab>
        <lesson name="basic01" icon="dothis">MVC Frameworks</lesson>
        <lesson name="dev01" icon="dothis">Devops Workflow Concepts</lesson>
        <lesson name="week02" icon="read">Survey results</lesson>
        <lab name="lab02">Collaborative Workflow</lab>
        <lesson name="dev02" icon="read">Gitflow Workflow Techniques (in lab)</lesson>
        <lesson name="dev03" icon="read">Gitflow Setup Example (in lab)</lesson>
        <lab name="lab02faq">Lab 2 FAQ</lab>
    </week>
    <week num="3">
        <topic>CodeIgniter &amp; Controllers</topic>         
        <outcomes>1.2 (controllers), 3</outcomes>
        <inlab>#3 Website conversion</inlab>
        <lesson name="basic01-ci" icon="dothis">CodeIgniter Overview</lesson>
        <lesson name="week03" icon="read" >Survey results - overview</lesson>
        <lab name="lab03">Website Conversion</lab>
        <tutorial name="ci-basic01">Static to Trivial CI Website Conversion</tutorial>
        <tutorial name="ci-basic02">Trivial CI to Basic CI Website Conversion</tutorial>
        <tutorial name="ci-basic03">Basic CI to Good CI Website Conversion</tutorial>
    </week>
    <week num="4">
        <topic>Routing</topic>         
        <outcomes>1.2 (routing), 3</outcomes>
        <inlab>#4 Working with controllers</inlab>
        <lesson name="basic02">CI Controllers</lesson>
        <lesson name="week03b" icon="read" >Survey results - controllers (last week)</lesson>
        <lesson name="basic06" icon="dothis">Routing</lesson>
        <lesson name="basic07" icon="read">Advanced Routing</lesson>
        <lesson name="week04" icon="read">Survey results - routing</lesson>
        <lab name="lab04">Working With Controllers &amp; Routing</lab>
        <tutorial name="ci-normal01">Controllers and Routing</tutorial>
    </week>
    <week num="5">
        <topic>Models</topic>
        <outcomes>1.2 (models), 3</outcomes>
        <inlab>Assignment #1 completion</inlab>
        <lesson name="basic03" icon="dothis"  survey="266872">CodeIgniter Models</lesson>
        <lesson name="basic03-more" icon="dothis" survey="266873">Model Pattenrs</lesson>
        <lesson name="week05" icon="read">Survey results - models</lesson>
        <lesson name="basic68">Models in a Nutshell</lesson>
        <assignment name="assignment1">Basic Webapp</assignment>
        <assignment name="assignment1faq" icon="read" >Assignment 1 FAQ</assignment> 
    </week>
    <week num="6">
        <topic>Views</topic>
        <outcomes>1.2 (views), 3</outcomes>
        <inlab>#5 Views</inlab>
        <lesson name="basic04-basics"  icon="dothis" >View Basics</lesson>
        <lesson name="week06" icon="read" >Survey results</lesson>
        <github name="views" link="https://github.com/jedi-academy/example-views" >Examples to support "views" lessons</github> 
        <lesson name="basic69">Views in a Nutshell</lesson>
        <!--		<assignment name="gallery1" icon="read" active="n">Project gallery</assignment>-->
        <lab name="lab05" >Todo List Manager</lab>
        <tutorial name="ci-todo01" >Database and models</tutorial>
        <tutorial name="ci-todo02" >Homepage Features</tutorial>
        <tutorial name="ci-todo03" >Ordered List Page Features</tutorial>
        <tutorial name="ci-todo05" >Help Wanted Page Features</tutorial>
    </week>
    <week num="7">
        <topic>Midterm exam week</topic>
    </week>
    <week num="8">
        <topic>Forms Handling</topic>
        <outcomes>1.2 (views), 3</outcomes>
        <inlab>#6 Model CRUD Prep</inlab>
        <lesson name="basic04-forms" icon="dothis">Creating Forms</lesson>
        <lesson name="basic04-handling" icon="dothis">Handling Form Data</lesson>
        <lesson name="week08" icon="read">Survey results</lesson>
        <lab name="lab06">Building Out Our TODO List</lab>
        <tutorial name="ci-todo04" >Maintenance List</tutorial>
        <tutorial name="ci-todo06">Pagination</tutorial>
        <tutorial name="ci-todo07">User Roles</tutorial>
    </week>
    <week num="9">
        <topic>Building on CodeIgniter</topic>
        <outcomes>1.3, 3</outcomes>
        <lesson name="basic05"  icon="dothis">Building on CodeIgniter</lesson>
        <lesson name="week09" icon="read">Survey results</lesson>
        <lesson name="basic70">Addins in a Nutshell</lesson>
        <lab name="lab07">Completing Our TODO List Build Out.</lab>
        <tutorial name="ci-todo08">Use RDB for sessions</tutorial>
        <tutorial name="ci-todo09">Install the Caboose Package</tutorial>
        <tutorial name="ci-todo10">Provide for Completing Work</tutorial>
        <tutorial name="ci-todo11">Role-specific Maintenance List</tutorial>
        <tutorial name="ci-todo12">Todo Item Maintenance (finally)</tutorial>
        <tutorial name="ci-todo11b">Polish the Item Maintenance</tutorial>
        <assignment name="assignment2">Functional Bot Factory</assignment>
        <assignment name="assignment2faq" icon="read" >Assignment 2 FAQ</assignment> 
    </week>
    <week num="10">
        <topic>Representation Glue - XML &amp; JSON</topic>
        <outcomes>2.1</outcomes>
        <lesson name="data01" icon="dothis" >X M L</lesson>
        <lesson name="data02"  icon="dothis" >J S O N</lesson>
        <lesson name="week10" icon="read">Survey results</lesson>
        <github name="xml" link="https://github.com/jedi-academy/example-xml">XML Examples</github>
        <github name="dataglue" link="https://github.com/jedi-academy/example-glue-data">Processing XML &amp; JSON (W.I.P.)</github>
    </week>
    <week num="11">
        <topic>Transport Glue - HTTP</topic>
        <outcomes>2.1, 2.2</outcomes>
        <lesson name="net01" icon="dothis">Transport Glue</lesson>
        <!--<lesson name="week11" icon="read" active="n">Survey results</lesson>
                        <github name="example-simplexml" link="https://github.com/jedi-academy/example-simplexml-winter2016" active="n">SimpleXML Examples</github>
        <lab name="lab08" active="n">Finishing Our Diner Build-out</lab>
        <tutorial name="xml-xml02" active="n">Handle Sales Orders With XML</tutorial>-->
    </week>
    <week num="12">
        <topic>Application Glue - REST</topic>
        <outcomes>2.1, 2.3</outcomes>
        <lesson name="advanced03" icon="dothis" survey="266882">REST</lesson>
        <lesson name="week12" icon="read">Survey results</lesson>
        <lab name="lab08">REST</lab>
        <tutorial name="tut-adv02">Decoupling Our Diner</tutorial>
    </week>
    <week num="13">
        <topic>Review</topic>
        <outcomes>2.1, 2.2, 2.3</outcomes>
        <lesson name="week13" icon="read">Survey results (the survey 
            link is in the "news" above).</lesson>
        <lesson name="final" >Final Exam Review</lesson>
        <!--		<lesson name="week13" icon="read" active="n">Survey results</lesson>
        <tutorial name="tut-adv01" active="n">Authentication</tutorial>-->
    </week>
    <week num="15">
        <topic>Final Exam Week</topic>
    </week>
    <week num="zz">
        <topic>REFERENCE</topic>
        <lesson name="intro02" icon="read" >Golden Rules</lesson>
        <tutorial name="setup03">PHP Comparison to Java</tutorial>
        <lesson name="dev04" icon="read" >Gitting Good</lesson>		
        <lesson name="marking" icon="read" >Marking Process</lesson>		
        <lesson name="webhooks" icon="read" >Webhooks for deployment testing</lesson>		
    </week>
    <week num="zz">
        <topic>FAQ</topic>
        <lesson name="faq-general" icon="read" >FAQ</lesson>		
        <lesson name="faq-apache" icon="read" >FAQ</lesson>		
        <lesson name="faq-devops" icon="read" >FAQ</lesson>		
        <lesson name="faq-ci" icon="read" >FAQ</lesson>		
    </week>
    <week num="yy">
        <topic>Other Frameworks (FYI)</topic>
        <lesson name="basic01-other" icon="read" >Other MVC Framework Examples</lesson>
        <lesson name="other-routing" icon="read">Routing examples from  other frameworks</lesson>
        <lesson name="other-models" icon="read" >Model examples from  other frameworks</lesson>
        <lesson name="other-controllers" icon="read" >Controller examples from other frameworks</lesson>
        <lesson name="other-views" icon="read" >View examples from  other frameworks</lesson>
        <lesson name="other-forms" icon="read" >Form examples from  other frameworks</lesson> 
        <lesson name="other-rest" icon="read" >REST examples from  other frameworks</lesson> 
    </week>
    <week num="xx">
        <topic>Supplementary Reading FYI</topic>
        <lesson name="basic04-leftovers"  icon="read">Other Form Techniques</lesson>
        <lesson name="xml01"  icon="read">XML Basics (Optional Refresher)</lesson>
        <lesson name="xml02"  icon="read">Constraining XML (Optional)</lesson>
        <lesson name="xml04" icon="read">Data Representation Conversions</lesson>
        <lesson name="advanced02"  icon="read">XML-RPC</lesson>
        <github name="xml" link="https://github.com/jedi-academy/example-xmlrpc" >XML-RPC Examples</github>
        <lesson name="advanced04" icon="read">AJAX</lesson>
        <lesson name="advanced01" icon="read">Authentication</lesson>
